name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: https://gist.github.com/ahnseongeun/bc65c106c149228515652ad9c49ad41d
          TIMEZONE: Asia/Seoul
